title: Fabian Schwarze

fields:
  live:
    label: Site Live
    type: toggle
    text:
      - Work in Progress
      - Live
    default: false

sections:
  pages:
    type: pages
    templates:
      - works
      - about
    create: false
